go: support for restoring work

diff --git a/bin/soda b/bin/soda
--- a/bin/soda
+++ b/bin/soda
@@ -93,6 +93,9 @@ function create_work()
     work=$(get_work_name)
     [ -z $work ] && exit
 
+    source_file=$($framework_dir/$ilang/work.sh source $work)
+    [ -e $source_file ] && { echo "Error: $source_file already exists" >&2; exit 2; }
+
     set -e
 
     docker_prepare
@@ -109,7 +112,6 @@ function create_work()
     # pull source file to local
     workdir=$($dku show $ilang workdir)
     container=$($dku show $ilang container)
-    source_file=$($framework_dir/$ilang/work.sh source $work)
     docker cp $container:$workdir/$source_file ./
 
     set +e
@@ -133,6 +135,8 @@ function parse_run_args()
             force_rebuild=yes
         elif [ "$t" == "--remote" ]; then
             remote_mode=yes
+        elif [ "$t" == "--restore" ]; then
+            restore_work=yes
         fi
         ((i++))
     done
@@ -157,6 +161,7 @@ function trans_lang_name()
 tags=
 force_rebuild=no
 remote_mode=no
+restore_work=no
 
 function lang_prepare()
 {
@@ -166,16 +171,38 @@ function lang_prepare()
     check_sdk $ilang
 }
 
+function restore_work_in_container()
+{
+    set -e
+
+    # remote work if exists
+    $dku rm-proj $ilang
+
+    # prepare working directory
+    prepare_working_dir
+
+    # create work
+    local work=$(get_work_name)
+    $dku play $ilang /soda/framework/$ilang/work.sh new $work
+}
+
 function run_work()
 {
-    docker_prepare && prepare_working_dir || exit
+    set -e
 
-    script="$dku play $ilang /soda/framework/$ilang/work.sh"
+    docker_prepare
+
+    if [ "$restore_work" == "yes" ]; then
+        restore_work_in_container
+    else
+        prepare_working_dir
+    fi
+
     work=$(get_work_name)
-
     source_file=$($framework_dir/$ilang/work.sh source $work)
     $dku sync-file $ilang $source_file
 
+    script="$dku play $ilang /soda/framework/$ilang/work.sh"
     # build executable
     [ "$force_rebuild" == "yes" ] && $script clean $work
     $script make $work || exit 
